name: Update README

on:
  schedule:
    - cron: "0 */1 * * *" # 매 시간 정각에 실행
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./profile

      - name: Run update script
        run: node readmeUpdate.js
        working-directory: ./profile

      - name: Commit README
        run: |
          git config --local user.name '${{ secrets.USER_NAME }}'
          git config --local user.email '${{ secrets.USER_EMAIL }}'
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m 'Update README with latest blog posts'
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GH_PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./profile
